### ISSUE TITLE
[FEATURE REQUEST]  ADD SUPPORT REACT 18

### ISSUE THREAD

**Issue by ronTabachnik** [Luehang/react-paypal-button-v2#130] opened 2022-09-04 04:31 UTC
*To add support for React 18!

**Comment by ivanoats** [comment] 2023-01-02 19:53
`npm install react-paypal-button-v2 --legacy-peer-deps`

**Comment by ivanoats** [comment] 2023-01-02 19:53
Duplicate of #123 , @ronTabachnik could you close this please?

**Closed** 2023-01-02 21:23 UTC
